# ⚠️ Automation/AI Policy:
# All code, dependency, and agent changes must pass secret scanning, license checks, tests, and AGENTS file update.
name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          cd scoutos-backend
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        env:
          DATABASE_URL: sqlite:///./test.db
        run: |
          cd scoutos-backend
          python -m pytest
