# ⚠️ Automation/AI Policy:
# All code, dependency, and agent changes must pass secret scanning, license checks, tests, and AGENTS file update.
name: BekonOS Dev/Test CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: devsecret1234567890abcdefg
      DATABASE_URL: postgresql://scoutos:devpass@localhost:5432/scoutos
      OPENAI_API_KEY: test-testkey-doesnotwork123456
      ENV: development
      MOCK_AI: "true"
      VITE_USE_MOCK_AI: "true"
      VITE_API_URL: http://localhost:8000
      VITE_ENV: development
      BEKONOS_CUSTOM_DOMAIN: dev.bekonos.local
      BEKONOS_ALLOWED_DOMAINS: localhost,127.0.0.1,scoutos.local,asr319.github.io,dev.bekonos.local,api.openai.com,registry.npmjs.org,pypi.org,pnpm.io,vitest.dev,github.com,files.pythonhosted.org

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Environment Variables
        run: |
          echo "SECRET_KEY=$SECRET_KEY"
          echo "DATABASE_URL=$DATABASE_URL"
          echo "BEKONOS_ALLOWED_DOMAINS=$BEKONOS_ALLOWED_DOMAINS"

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: npm install -g pnpm corepack

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install backend requirements
        run: |
          cd bekonos-backend
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Install frontend requirements
        run: |
          cd bekonos-frontend
          pnpm install

      - name: Initialize database if script exists
        run: |
          cd bekonos-backend
          if [ -f scripts/init_db.py ]; then
            python scripts/init_db.py
          else
            echo "No DB initialization script found. Please run migrations if needed."
          fi
          cd ..

      - name: Run backend tests
        run: |
          cd bekonos-backend
          pytest || echo "No backend tests found."

      - name: Run frontend tests
        run: |
          cd bekonos-frontend
          pnpm test || echo "No frontend tests found."

      - name: List directories for debug
        run: ls -l

      - name: Success message
        run: echo "BekonOS dev/test environment CI script completed!"
