# ⚠️ Automation/AI Policy:
# All code, dependency, and agent changes must pass secret scanning, license checks, tests, and AGENTS file update.
name: Full Checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
      - name: Repo history scan
        run: gitleaks detect --redact --no-git --source .
      - name: Custom secret scan
        run: python scripts/scan_for_secrets.py

  audit-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
        working-directory: scoutos-frontend
      - run: pnpm audit --audit-level high
        working-directory: scoutos-frontend
    permissions:
      contents: read

  audit-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r scoutos-backend/requirements.txt -r scoutos-backend/requirements-dev.txt pip-audit
      - run: pip-audit
    permissions:
      contents: read

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: npm install -g pnpm
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: pnpm lint
        working-directory: scoutos-frontend

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r scoutos-backend/requirements.txt -r scoutos-backend/requirements-dev.txt flake8 black
      - run: flake8 scoutos-backend
      - run: black --check scoutos-backend

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: npm install -g pnpm
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: pnpm test -- --run
        working-directory: scoutos-frontend

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r scoutos-backend/requirements.txt -r scoutos-backend/requirements-dev.txt pytest
      - run: pytest --cov=scoutos-backend --cov-fail-under=85
        working-directory: scoutos-backend

  duplicate-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python scripts/check_duplicates.py

  agents-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python scripts/validate_agents.py

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: npm install -g pnpm prettier
      - run: pip install pyspelling
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: prettier --check .
        working-directory: scoutos-frontend
      - run: pyspelling
      - run: black --check scoutos-backend

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: npm install -g license-checker
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: license-checker --summary
        working-directory: scoutos-frontend
      - run: pip install pip-licenses
      - run: pip-licenses --fail-on non-free

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: pnpm audit --audit-level high
        working-directory: scoutos-frontend
      - run: pip install bandit
      - run: bandit -r scoutos-backend

  dead-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: npx depcheck
        working-directory: scoutos-frontend
      - run: pip install vulture
      - run: vulture scoutos-backend

  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: npm install -g pnpm
      - run: pnpm install
        working-directory: scoutos-frontend
      - run: npx axe ./index.html
        working-directory: scoutos-frontend

  container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: "docker.io/library/python:3.11"

  changelog-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python scripts/check_changelog.py

  history-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --no-git -v
