# ⚠️ Automation/AI Policy:
# All code, dependency, and agent changes must pass secret scanning, license checks, tests, and AGENTS file update.
name: Deploy BekonOS Frontend to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g pnpm corepack
      - name: Install frontend dependencies
        run: |
          cd scoutos-frontend
          pnpm install
      - name: Set build environment variables
        run: |
          cd scoutos-frontend
          echo "VITE_API_URL=https://your-backend-endpoint.com" >> .env
          echo "VITE_ENV=production" >> .env
          echo "VITE_USE_MOCK_AI=false" >> .env
          echo "SCOUTOS_CUSTOM_DOMAIN=dev.scoutos.local" >> .env
          echo "SCOUTOS_ALLOWED_DOMAINS=localhost,127.0.0.1,scoutos.local,asr319.github.io,dev.scoutos.local,api.openai.com,registry.npmjs.org,pypi.org,pnpm.io,vitest.dev,github.com,files.pythonhosted.org" >> .env
      - name: Build static site
        run: |
          cd scoutos-frontend
          pnpm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: scoutos-frontend/dist
